### PR TITLE
Pool server for equihash solution <n, k>

### PR DESCRIPTION
**Pull request by ghost**
This PR, together with those to be applied on equihashverify and node-stratum-poo, allows to install a pool server based on z-nomp able to manage and validate the following equihash solutions:
- n = 48, k = 5
- n = 96, k = 3
- n = 96, k = 5
- n = 192, k = 7
- n = 200, k = 9

**Supported equihash algorithm options:**
- Equihash48_5 
- Equihash96_3 
- Equihash96_5 
- Equihash144_5 
- Equihash192_7 
- Equihash200_9

**Dependencies:**
https://github.com/ZencashOfficial/equihashverify/pull/2
https://github.com/z-classic/node-stratum-pool/pull/35

### CODE REVIEW

**Comment by tarrenj** [comment]
Concept ACK, also see https://github.com/NickRHill/zh-nomp

**Comment by litecoinz-project** [comment]
They accept only _equihash_ as coin algorithm parameter. That implementation precludes the use of z-nomp in a generic way for all the variants of equihash (n = 200 / k = 9, n = 144 / k = 5, n = 192 / k = 7, etc etc) because these parameters are hard-coded in their equihashverify fork and not passed as in my implementation from z-nomp coin configuration:
```
z-nomp -> node-stratum-pool -> equihashverify 
```

**Comment by litecoinz-project** [comment]
See also PR https://github.com/ZencashOfficial/node-stratum-pool/pull/1

**Comment by tarrenj** [comment]
We're not maintaining this anymore, you'll have much better success over at the S-NOMP repo: https://github.com/s-nomp  I think they've already implemented this though.

**Pull request closed without merging**
